CREATE TABLE app_user (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_id     VARCHAR(255) UNIQUE,
    first_name  VARCHAR(255) NOT NULL,
    last_name   VARCHAR(255),
    email       VARCHAR(255),
    phone       VARCHAR(255),
    whatsapp    VARCHAR(255),
    role        VARCHAR(255) NOT NULL          -- 'PENPAL','PARENT_HELPER','MONITOR','ADMIN'
);

-- JOINED inheritance: a penpal is an app_user row + a penpal row sharing the same id
CREATE TABLE penpal (
    id               BIGINT        PRIMARY KEY,
    age              INTEGER,
    state            VARCHAR(255) NOT NULL,     -- State enum name: US state code (CA, TX...) or Malawi region (NORTH/CENTRAL/SOUTH)
    biography        VARCHAR(2000),
    parent_helper_id BIGINT        NOT NULL,     -- @ManyToOne AppUser parentHelper (a PARENT_HELPER guardian)
    CONSTRAINT fk_penpal_user          FOREIGN KEY (id)               REFERENCES app_user(id),
    CONSTRAINT fk_penpal_parent_helper FOREIGN KEY (parent_helper_id) REFERENCES app_user(id)
);

CREATE TABLE chat (
    id     BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active BOOLEAN
);

-- @ManyToMany Chat.members (List<Penpal>). "exactly two penpals" is app logic, not a constraint.
CREATE TABLE chat_members (
    chat_id    BIGINT NOT NULL,
    members_id BIGINT NOT NULL,
    PRIMARY KEY (chat_id, members_id),
    CONSTRAINT fk_cm_chat   FOREIGN KEY (chat_id)    REFERENCES chat(id),
    CONSTRAINT fk_cm_penpal FOREIGN KEY (members_id) REFERENCES penpal(id)
);

CREATE TABLE message (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text            VARCHAR(2000) NOT NULL,
    penpal_author_id   BIGINT        NOT NULL,     -- author is a penpal
    performed_by_id    BIGINT        NOT NULL,     -- logged in user parenhelper probably
    create_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    chat_id         BIGINT        NOT NULL,
    approved        BOOLEAN,
    approved_by_id  BIGINT,                     -- app rule: MUST be a MONITOR
    approved_time   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_msg_author  FOREIGN KEY (penpal_author_id)  REFERENCES penpal(id),
    CONSTRAINT fk_msg_creator  FOREIGN KEY (performed_by_id)  REFERENCES app_user(id),
    CONSTRAINT fk_msg_chat     FOREIGN KEY (chat_id)        REFERENCES chat(id),
    CONSTRAINT fk_msg_approver FOREIGN KEY (approved_by_id) REFERENCES app_user(id)
);

CREATE TABLE message_audit (
    audit_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    archive_time    TIMESTAMP WITH TIME ZONE,
    edited_by_id    BIGINT,                     -- app rule: creator | their helper | any monitor
    ------------------------
    message_id      BIGINT,                     -- FK -> message
    text            VARCHAR(2000) NOT NULL,
    penpal_author_id   BIGINT        NOT NULL,     -- author is a penpal
    performed_by_id    BIGINT        NOT NULL,     -- logged in user parenhelper probably
    create_time     TIMESTAMP WITH TIME ZONE NOT NULL,
    chat_id         BIGINT        NOT NULL,
    approved        BOOLEAN,
    approved_by_id  BIGINT,
    approved_time   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_ma_message  FOREIGN KEY (message_id)     REFERENCES message(id),
    CONSTRAINT fk_ma_editor   FOREIGN KEY (edited_by_id)   REFERENCES app_user(id),
    CONSTRAINT fk_ma_author  FOREIGN KEY (penpal_author_id)  REFERENCES penpal(id),
    CONSTRAINT fk_ma_creator  FOREIGN KEY (performed_by_id)  REFERENCES app_user(id),
    CONSTRAINT fk_ma_chat     FOREIGN KEY (chat_id)        REFERENCES chat(id),
    CONSTRAINT fk_ma_approver FOREIGN KEY (approved_by_id) REFERENCES app_user(id)
);
